# Generated by Django 3.1.1 on 2021-01-05 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_support_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
