# Generated by Django 3.1.1 on 2020-12-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_and_fit',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('One Size', 'One Size'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='S', max_length=20),
        ),
    ]
