# Generated by Django 3.1.1 on 2021-01-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
    ]
