# Generated by Django 3.1.1 on 2021-01-02 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210102_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='meta_description',
            new_name='description',
        ),
    ]
