# Generated by Django 3.1.1 on 2021-01-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210104_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(to='shop.Product'),
        ),
    ]
