# Generated by Django 3.1.1 on 2021-01-05 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_support_supportlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
