# Generated by Django 3.1.1 on 2020-12-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address2',
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
